### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by meowsbits** [wanchain/wan-wallet-desktop#41]
This prevents `npm run dev` from succeeding, too.

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
ubp52 ~/dev/wanchain/wan-wallet-desktop master=
> node --version
v13.7.0
ubp52 ~/dev/wanchain/wan-wallet-desktop master=
> npm --version
6.14.5
ubp52 ~/dev/wanchain/wan-wallet-desktop master=
> git rev-parse HEAD
7c7470eca3c3358bf7740c2a514c71741c80fce9
```

```
> npm i
[...]
scrypt.target.mk:131: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/ia/dev/wanchain/wan-wallet-desktop/node_modules/scrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ia/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.2.9-050209-generic
gyp ERR! command "/home/ia/.nvm/versions/node/v13.7.0/bin/node" "/home/ia/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ia/dev/wanchain/wan-wallet-desktop/node_modules/scrypt
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"13.7.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-i18next@10.13.2 requires a peer of i18next@>= 17.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ia/.npm/_logs/2020-06-26T12_22_12_853Z-debug.log

```

Full gist of `/home/ia/.npm/_logs/2020-06-26T12_22_12_853Z-debug.log` here: https://gist.github.com/43ab91abdd8e921508acc56fea017356

**Comment by JasonHJ** [comment]
Try using the 10.16.0 version of Node
